version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/app.docker
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle:cached
    ports:
      - "3000:3000"
  webpack-dev-server:
    build:
      context: .
      dockerfile: ./docker/webpack-dev-server.docker
    command: npm run serve
    volumes:
      - ./public/packs:/myapp/public/packs
      - ./app/javascript:/myapp/app/javascript
    ports:
      - "8081:8081"
    depends_on:
      - web
volumes:
  bundle:
    driver: local
